name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Building on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
         - os: ubuntu-latest
           artifact_name: zssh
           asset_name: zssh-linux-amd64
         - os: windows-latest
           artifact_name: zssh.exe
           asset_name: zssh-windows-amd64.exe
         - os: macos-latest
           artifact_name: zssh
           asset_name: zssh-macos-amd64
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Make the build dir
      run: mkdir "${{ runner.workspace }}/build"
      
    - name: Build
      run: go build -o ${{ runner.workspace }}/build ./... 

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ runner.workspace }}/build/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: latest-tag
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ runner.workspace }}/build/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
