name: build

on:
  push:
    branches:
      - main
      - release-v*
  pull_request:
    branches:
      - main

jobs:
  mac-os-build:
    name: Build Mac OS binaries
    runs-on: macos-10.15
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
    
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'

      - name: Install Dependencies
        run: |
          go tidy

      - name: Build
        run: |
          go build -v ./...



  windows-build:
    name: Build Windows binaries
    runs-on: windows-2019
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'

      - name: Build and Test
        shell: bash
        run: |
         go build -v ./...
         
  tag-and-publish:
    name: Build Linux Binaries, Tag and Publish
    runs-on: ubuntu-18.04
    needs: [ mac-os-build, windows-build ]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
    
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'

      - name: Install Ziti CI
        run: | 
          go tidy

      - name: Build
        run: |
          go build -v ./...   
        
      - name: Publish
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release-v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $(go env GOPATH)/bin/zssh tag -v -f version
          $(go env GOPATH)/bin/zssh publish-to-github

